apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hsgs6g5ug-nodejs 
  janus-idp.io/tekton: hsgs6g5ug-nodejs
  backstage.io/kubernetes-id: hsgs6g5ug-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hsgs6g5ug-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml