apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hsgs6g5ug-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hsgs6g5ug-nodejs 
  name: hsgs6g5ug-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: hsgs6g5ug-nodejs 
